# =========================
# Low-Latency FlexSDR Config
# =========================
eal:
  file_prefix: "flexsdr-app"          # same across all processes
  huge_dir: "/dev/hugepages"
  socket_mem: "512,512"             # Increased memory allocation
  no_pci: true
  iova: "va"                          # switch to "PA" when using NIC DMA

defaults:
  nb_mbuf: 8192                       # Increased for better flow control
  mp_cache: 256                       # Larger cache for better performance
  ring_size: 512                      # Reduced for lower latency
  data_format: "cs16"                 # I16,Q16 => 4 bytes/complex
 
  # Streamer defaults (can be overridden per app)
  tx_stream:
    num_channels: 2
    allow_partial: true
    timeout_us: 10                    # Reduced timeout
  rx_stream:
    num_channels: 4
    allow_partial: true
    timeout_us: 10                    # Reduced timeout

primary:
  pools:
    # Optimized for SPP=64: 64 × 4B × 4ch = 1024B + headers ≈ 2048B
    - { name: "inbound_pool",   size: 8192, elt_size: 2048 }
    - { name: "outbound_pool",  size: 8192, elt_size: 2048 }

  rings:
    # Reduced ring sizes for lower latency
    - { name: "inbound_ring",   size: 512 }

    # per-channel TX rings (UE -> primary) (SPSC each)
    - { name: "tx_ch1",         size: 512 }
    - { name: "tx_ch2",         size: 512 }
